### ISSUE TITLE
[Question] ECMAScript module syntax ?

### ISSUE THREAD

**Issue by jmesa-sistel** [appvision-gmbh/json2typescript#147] opened 2020-06-25 10:34 UTC
Hello I am using angular 10 and I get a warning when I use the library.

```
WARNING in \src\webapp\src\app\services\app-globals.service.ts depends on json2typescript. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```
But I think the library is using ECMAScript module syntax, maybe is related how is build?.

**Comment by rayita** [comment] 2020-06-26 09:01
Same issue here.

The problem is line 10 of tsconfig.json

    "module": "commonjs",

it must be "esnext" or "es2020" to avoid this warning (and optimization issues).

**Comment by andreas-aeschlimann** [comment] 2020-06-26 09:04
Hi all, that sounds bad.

Is that all we need to fix it? Can you provide a PR?

**Comment by rayita** [comment] 2020-06-29 11:36
Yo got it #148

**Comment by andreas-aeschlimann** [comment] 2020-06-29 14:24
I will merge it and a release a new version soon.

Thanks!

**Comment by andreas-aeschlimann** [comment] 2020-07-17 13:52
Closed by #148

**Closed by andreas-aeschlimann** 2020-07-17 13:52 UTC
Labels: invalid

**Comment by tobiasschweizer** [comment] 2020-09-07 07:29
> I will merge it and a release a new version soon.
> 
> Thanks!

Will there be a new version on npm soon?

**Comment by andreas-aeschlimann** [comment] 2020-09-07 22:39
There is still a problem with the PR which I mentioned in the PR itself.

Basically all imports in all files have to be redefined if we apply the PR. I don't know yet how to solve this issue.

**Comment by tobiasschweizer** [comment] 2020-09-08 06:39
> Basically all imports in all files have to be redefined if we apply the PR.

I had had to set the option `"moduleResolution": "node"`to make my existing imports work.

**Comment by musicEnfanthen** [comment] 2020-09-08 07:48
@jmesa-sistel  @rayita As a workaround (until the corresponding PR is merged), you can allow a CommonJs dependency in your `angular.json`:

```
 "architect": {
                "build": {
                    "builder": "@angular-devkit/build-angular:browser",
                    "options": {
                        ...
                        "allowedCommonJsDependencies": [
                            "json2typescript"
                           ],
}}}
```

**Comment by tobiasschweizer** [comment] 2020-09-08 08:11
> @jmesa-sistel @rayita As a workaround (until the corresponding PR is merged), you can allow a CommonJs dependency in your `angular.json`:
> 
> ```
>  "architect": {
>                 "build": {
>                     "builder": "@angular-devkit/build-angular:browser",
>                     "options": {
>                         ...
>                         "allowedCommonJsDependencies": [
>                             "json2typescript"
>                            ],
> }}}
> ```

I think this just [suppresses](https://angular.io/guide/build#configuring-commonjs-dependencies) the warning, right?

**Comment by musicEnfanthen** [comment] 2020-09-08 08:28
Yes, of course. It is just a temporary solution until the PR is merged.

**Comment by andreas-aeschlimann** [comment] 2020-09-08 22:32
> > Basically all imports in all files have to be redefined if we apply the PR.
> 
> I had had to set the option `"moduleResolution": "node"`to make my existing imports work.

What does it do?

**Comment by tobiasschweizer** [comment] 2020-09-09 08:03
In my project, I directly import JSON files using `import` (`"resolveJsonModule": true,`). After setting `module` to "es6" (from "commonjs") I got errors which I could fix by using the "moduleResolution" option. 

> Note: node module resolution is the most-commonly used in the TypeScript community and is recommended for most projects. If you are having resolution problems with imports and exports in TypeScript, try setting moduleResolution: "node" to see if it fixes the issue.

https://www.typescriptlang.org/docs/handbook/module-resolution.html#module-resolution-strategies  

I don't really understand why this does in combination with "`module: es6`" but it works for me.
